export const APP_ROUTES = {
    login: 'login',
    loginLawyer: 'loginLawyer',
    signin: 'signin',
    signup : 'signup',
    signupLawyer: 'signupLawyer',
    signupClient: 'signupClient',
    problem: 'problem',
    profileLawyer: 'profileLawyer',
    profileClient: 'profileClient',
    lawyerCases: 'lawyerCases',
    lawyerSpace: 'lawyerSpace',
    scroll1: 'scroll1',
    scroll2: 'scroll2',
    scroll3: 'scroll3',
    scroll4: 'scroll4',
}